// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtxarD65Gl8ZMJqD0jHmCIWR5Jbkc99g0',
    appId: '1:902226941081:web:d5456b555f680d01ccd408',
    messagingSenderId: '902226941081',
    projectId: 'finance-tracker-d90af',
    authDomain: 'finance-tracker-d90af.firebaseapp.com',
    storageBucket: 'finance-tracker-d90af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwcsKUjEWi2MMzHAV8rItZh1YxZ58Kyl4',
    appId: '1:902226941081:android:5d3783fd9e070405ccd408',
    messagingSenderId: '902226941081',
    projectId: 'finance-tracker-d90af',
    storageBucket: 'finance-tracker-d90af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2enEBev3wGOLAbIntlt07Zh5WeVZKLEQ',
    appId: '1:902226941081:ios:c5b3d5ecdd3bc9c6ccd408',
    messagingSenderId: '902226941081',
    projectId: 'finance-tracker-d90af',
    storageBucket: 'finance-tracker-d90af.appspot.com',
    iosBundleId: 'com.example.habit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2enEBev3wGOLAbIntlt07Zh5WeVZKLEQ',
    appId: '1:902226941081:ios:98e17fa7bd75724cccd408',
    messagingSenderId: '902226941081',
    projectId: 'finance-tracker-d90af',
    storageBucket: 'finance-tracker-d90af.appspot.com',
    iosBundleId: 'com.example.habit.RunnerTests',
  );
}
